### ISSUE TITLE
identify parser does not handle a set, such as IPTC Keywords.

### ISSUE THREAD

**Issue by cwholt** [mceachen/micro_magick#3]
using this code:
```
require 'tempfile'
require 'open-uri'
require 'micro_magick'

onion_url = "http://www.photometadata.org/sites/default/files/farmer_onion.jpg"

tf = Tempfile.new(%w{ onion_farmer .jpg })
tf.binmode
open(onion_url, {}) { |bits| tf.write(bits.read) }
final_cmd = "identify -verbose #{tf.path}"
stdout = Open3.popen3(final_cmd) do |stdin, stdout, stderr|
  stdout.read.strip
end
tf.close
tf.unlink
results = MicroMagick::IdentifyParser.new(stdout)
results[:profiles][:profile_iptc][:keyword_2_25_] # "Leeks"
```
However, this example file should have 45 keywords!

```MicroMagick::IdentifyParser``` simply sets the last seen key https://github.com/mceachen/micro_magick/blob/5fd73cd745da0c346ac7e1d9a9808be36b586b86/lib/micro_magick/identify_parser.rb#L32 but it should create an array.

**Comment by mceachen** [comment]
I've just released v1.0.0 which greatly simplifies `identify` parsing to only support dimensions (which is required by the other functions. All the other attributes, like EXIF headers, were pretty hacky—no correct types, nesting was inconsistent, and paths changed across versions of ImageMagick and GraphicsMagick.

I've updated the README to point people to the [exiftool](https://github.com/mceachen/exiftool) and [exiftool_vendored](https://github.com/mceachen/exiftool_vendored) gems for this use case.
