### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by smikkelsen** [mceachen/micro_magick#7]
I went through similar trouble with rmagick bouncing back and forth from 1 forum to the next, some with cli syntax, others with object based syntax, and more or less had to guess my way into a working solution.

I like the promise of lighter and faster processing with micro_magick / graphics magick, but i'm back to ground zero on figuring out how to use it. 

Do you have a reference somewhere?

For example, I was previously using the following method to take in-memory blobs and create an animated gif with them.
```
  def gif_blob(blobs)
    gif = Magick::ImageList.new
    gif.from_blob *blobs
    gif.delay = delay if delay
    gif.iterations = 1 if @expired
    gif.scene = scene if scene
    gif.ticks_per_second = ticks_per_second if ticks_per_second
    # gif = gif.coalesce
    gif = gif.optimize_layers Magick::OptimizeLayer if blobs.count > 1
    # out = Rails.root.join('tmp', "#{@timer.id.to_s}_out.gif")
    # gif.write out
    blob = gif.to_blob do |attrs|
      attrs.format = 'gif'
      # attrs.quality = 1
      # attrs.density = 8
    end
    gif.destroy!
    blob
  end
```

Simply changing Magick::ImageList.new to MicroMagic::ImageList.new doesn't work. There is no "from_blob" method apparently, so its not a drop in replacement unfortunately.

I'm excited to give this a try, but I don't have days to figure it out. Any help would be greatly appreciated!

**Comment by mceachen** [comment]
This gem is a very light wrapper to help generate valid ARGV for both
graphicsmagick and imagemagick. There is no special API other than what is
described in the readme.

First get a convert or gm command that does what you want. Then follow the
readme example to see how to translate that to this gem's API.
